# Generated by Django 3.2.16 on 2024-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_video_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.TextField(),
        ),
    ]
