# Generated by Django 3.2.16 on 2024-07-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_video_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_creation',
        ),
    ]
